### ISSUE TITLE
Data length for AES in binary data AES encryption/decryption example

### ISSUE THREAD

**Issue by asavchuk** [alexgoussev/aes_crypt#5]
Error for example of binary data AES encryption/decryption:
  

```
      Uint8List key = Uint8List.fromList(
          [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]);
      Uint8List iv = Uint8List.fromList(
          [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]);
    
      var crypt = AesCrypt('my cool password');
      crypt.aesSetParams(key, iv, AesMode.cbc);
    
      Uint8List srcData = Uint8List.fromList([1, 2, 3, 4, 5]);
    
      Uint8List encryptedData = crypt.aesEncrypt(srcData); // error on this line
      Uint8List decryptedData = crypt.aesDecrypt(encryptedData);
```

>     Invalid argument(s): Invalid data length for AES: 5 bytes.
>     #0      _Aes.aesEncrypt (package:aes_crypt/src/aes.dart:244:7)
>     #1      AesCrypt.aesEncrypt (package:aes_crypt/src/aescrypt.dart:370:48)
>     #2      main (package:aestest/aes.dart:36:35)
>     #3      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
>     #4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)

**Comment by 308066400** [comment]
bug：

  Uint8List aesEncrypt(Uint8List data) {
    AesCryptArgumentError.checkNullOrEmpty(_aesKey, 'AES encryption key is null or empty.');
    if (_aesMode != AesMode.ecb && _aesIV.isEmpty) {
      throw AesCryptArgumentError('The initialization vector is empty. It can not be empty when AES mode is not ECB.');
    } else if (data.length % 16 != 0) {
      throw AesCryptArgumentError('Invalid data length for AES: ${data.length} bytes.');
    }
